name: Deploy Client to Firebase Hosting

on:
  push:
    branches:
      - main  # Change this to your deployment branch if different
    paths:
      - 'client/**'  # Trigger workflow only when files in client/ change

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client  # Set working directory to client folder

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Change to match your project

      - name: Install Dependencies
        run: npm install  # Use yarn or pnpm if needed

      - name: Build Project
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live  # Deploys to production
          projectId: future-blogs
