name: Preview Client on Firebase Hosting for PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'client/**'  # Run only when files in client/ change

jobs:
  preview:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client  # Run commands inside client/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy Preview to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: preview
          entryPoint: client  # 🔥 Tell Firebase to look inside client/
          projectId: future-blogs
